<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Uom;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category' => 'Engine Parts',
                'brand' => 'Toyota',
                'uom' => 'pcs',
                'name' => 'Oil Filter',
                'sku' => 'ENG-TOY-OF-001',
                'part_number' => '04152-YZZA1',
                'model_no' => 'Corolla 2014-2019',
                'origin_country' => 'Japan',
                'hs_code' => '84212300',
                'purchase_price' => 450,
                'sales_price' => 650,
                'reorder_level' => 20,
            ],
            [
                'category' => 'Engine Parts',
                'brand' => 'Honda',
                'uom' => 'pcs',
                'name' => 'Air Filter',
                'sku' => 'ENG-HON-AF-002',
                'part_number' => '17220-RNA-A00',
                'model_no' => 'Civic 2012-2016',
                'origin_country' => 'Thailand',
                'hs_code' => '84213100',
                'purchase_price' => 700,
                'sales_price' => 950,
                'reorder_level' => 15,
            ],
            [
                'category' => 'Engine Parts',
                'brand' => 'Nissan',
                'uom' => 'pcs',
                'name' => 'Timing Belt',
                'sku' => 'ENG-NIS-TB-003',
                'part_number' => '13028-4M500',
                'model_no' => 'Sunny N16',
                'origin_country' => 'Japan',
                'hs_code' => '40103500',
                'purchase_price' => 1850,
                'sales_price' => 2400,
                'reorder_level' => 8,
            ],
            [
                'category' => 'Engine Parts',
                'brand' => 'Denso',
                'uom' => 'pcs',
                'name' => 'Spark Plug',
                'sku' => 'ENG-DEN-SP-004',
                'part_number' => 'K20HR-U11',
                'model_no' => 'Universal Petrol Engine',
                'origin_country' => 'Indonesia',
                'hs_code' => '85111000',
                'purchase_price' => 280,
                'sales_price' => 420,
                'reorder_level' => 50,
            ],
            [
                'category' => 'Brake Parts',
                'brand' => 'Toyota',
                'uom' => 'set',
                'name' => 'Front Brake Pad Set',
                'sku' => 'BRK-TOY-FBP-005',
                'part_number' => '04465-02220',
                'model_no' => 'Corolla 2014-2019',
                'origin_country' => 'Japan',
                'hs_code' => '87083000',
                'purchase_price' => 2200,
                'sales_price' => 2950,
                'reorder_level' => 10,
            ],
            [
                'category' => 'Brake Parts',
                'brand' => 'Honda',
                'uom' => 'set',
                'name' => 'Rear Brake Shoe Set',
                'sku' => 'BRK-HON-RBS-006',
                'part_number' => '43153-S5A-J01',
                'model_no' => 'City 2009-2013',
                'origin_country' => 'Thailand',
                'hs_code' => '87083000',
                'purchase_price' => 1650,
                'sales_price' => 2250,
                'reorder_level' => 12,
            ],
            [
                'category' => 'Brake Parts',
                'brand' => 'Bosch',
                'uom' => 'ltr',
                'name' => 'DOT 4 Brake Fluid',
                'sku' => 'BRK-BOS-BF-007',
                'part_number' => '1987479106',
                'model_no' => 'DOT 4',
                'origin_country' => 'Germany',
                'hs_code' => '38190000',
                'purchase_price' => 520,
                'sales_price' => 750,
                'reorder_level' => 25,
            ],
            [
                'category' => 'Brake Parts',
                'brand' => 'Nissan',
                'uom' => 'pcs',
                'name' => 'Brake Disc Rotor',
                'sku' => 'BRK-NIS-BDR-008',
                'part_number' => '40206-4M400',
                'model_no' => 'Sunny N16',
                'origin_country' => 'Japan',
                'hs_code' => '87083000',
                'purchase_price' => 3100,
                'sales_price' => 3950,
                'reorder_level' => 6,
            ],
            [
                'category' => 'Suspension Parts',
                'brand' => 'Toyota',
                'uom' => 'pcs',
                'name' => 'Front Shock Absorber',
                'sku' => 'SUS-TOY-FSA-009',
                'part_number' => '48520-09J70',
                'model_no' => 'Axio 2012-2018',
                'origin_country' => 'Japan',
                'hs_code' => '87088000',
                'purchase_price' => 4200,
                'sales_price' => 5400,
                'reorder_level' => 6,
            ],
            [
                'category' => 'Suspension Parts',
                'brand' => 'Honda',
                'uom' => 'pcs',
                'name' => 'Lower Control Arm',
                'sku' => 'SUS-HON-LCA-010',
                'part_number' => '51360-SNA-A03',
                'model_no' => 'Civic 2006-2011',
                'origin_country' => 'Thailand',
                'hs_code' => '87088000',
                'purchase_price' => 3600,
                'sales_price' => 4700,
                'reorder_level' => 5,
            ],
            [
                'category' => 'Suspension Parts',
                'brand' => 'Nissan',
                'uom' => 'set',
                'name' => 'Stabilizer Link Set',
                'sku' => 'SUS-NIS-SLS-011',
                'part_number' => '54618-4M400',
                'model_no' => 'Sunny N16',
                'origin_country' => 'Japan',
                'hs_code' => '87088000',
                'purchase_price' => 1250,
                'sales_price' => 1800,
                'reorder_level' => 10,
            ],
            [
                'category' => 'Electrical Parts',
                'brand' => 'Denso',
                'uom' => 'pcs',
                'name' => 'Alternator Assembly',
                'sku' => 'ELE-DEN-ALT-012',
                'part_number' => '104210-3290',
                'model_no' => 'Toyota 1NZ-FE',
                'origin_country' => 'Japan',
                'hs_code' => '85115000',
                'purchase_price' => 8900,
                'sales_price' => 11200,
                'reorder_level' => 3,
            ],
            [
                'category' => 'Electrical Parts',
                'brand' => 'Bosch',
                'uom' => 'pcs',
                'name' => 'Starter Motor',
                'sku' => 'ELE-BOS-STM-013',
                'part_number' => '0001107402',
                'model_no' => 'Universal 12V',
                'origin_country' => 'Germany',
                'hs_code' => '85114000',
                'purchase_price' => 7600,
                'sales_price' => 9800,
                'reorder_level' => 4,
            ],
            [
                'category' => 'Electrical Parts',
                'brand' => 'Toyota',
                'uom' => 'pcs',
                'name' => 'Headlight Bulb H4',
                'sku' => 'ELE-TOY-HB4-014',
                'part_number' => '90981-13046',
                'model_no' => 'H4 12V 60/55W',
                'origin_country' => 'Japan',
                'hs_code' => '85392100',
                'purchase_price' => 250,
                'sales_price' => 380,
                'reorder_level' => 40,
            ],
            [
                'category' => 'Electrical Parts',
                'brand' => 'Honda',
                'uom' => 'box',
                'name' => 'Fuse Assortment Box',
                'sku' => 'ELE-HON-FAB-015',
                'part_number' => '38200-SDA-A01',
                'model_no' => 'Mini Blade Fuse',
                'origin_country' => 'China',
                'hs_code' => '85361000',
                'purchase_price' => 600,
                'sales_price' => 900,
                'reorder_level' => 15,
            ],
        ];

        foreach ($products as $product) {
            $category = ProductCategory::where('name', $product['category'])->firstOrFail();
            $brand = Brand::where('name', $product['brand'])->firstOrFail();
            $uom = Uom::where('short_name', $product['uom'])->firstOrFail();

            Product::updateOrCreate(
                ['sku' => $product['sku']],
                [
                    'category_id' => $category->id,
                    'brand_id' => $brand->id,
                    'uom_id' => $uom->id,
                    'name' => $product['name'],
                    'slug' => Str::slug($product['name'].'-'.$product['sku']),
                    'part_number' => $product['part_number'],
                    'model_no' => $product['model_no'],
                    'origin_country' => $product['origin_country'],
                    'hs_code' => $product['hs_code'],
                    'purchase_price' => $product['purchase_price'],
                    'sales_price' => $product['sales_price'],
                    'reorder_level' => $product['reorder_level'],
                    'is_active' => true,
                ]
            );
        }
    }
}
